services:
  - type: cron
    name: atualiza_produto_atual
    env: python
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: "python api_linx_azure.py"
    schedule: "0 6 * * *"  # 06h UTC = 03h da manhã (horário de Brasília)
